name: movies_list_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.4

  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  injectable: ^1.2.2
  json_annotation: ^4.0.1
  bloc: ^7.0.0
  dartz: 0.10.0-nullsafety.1
  rxdart: ^0.26.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.1

flutter:

  uses-material-design: true